name: update deployment

# Triggers on push or merge to the master branch
on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v3

      - name: use node.js 16.19.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.19.0'

      - name: install and build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: build
