name: PR Build Check

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          yarn install --frozen-lockfile
          yarn build
