name: Test PRs

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

permissions:
  pull-requests: write # To comment on PRs
  issues: write        # To comment on PRs

jobs:
  test:
    if: github.event_name == 'pull_request' || contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
      - name: Test PR
        uses: phucbm/test-pr-action@v1
        